In [ ]:
sentences = [
    "I am Vamshidhar H K, working as a data scientist at Flytxt",
    "I am a native of Andhra pradesh",
    "I am passionate about data analytics in various domains Teleco, banking and health care",
    "I am currnelty focussed on leanring NLP from Coursera",
    "I admire proff. Gilbert strang as he teaches Maths in a most simplest way.",
    "You are awesome!"
]
### Tokenization:
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")

tokenized_sentences = []
for sent in sentences:
    tokenized_sentences.append(tokenizer(sent)) # tokenizer requires each sample and not the list of samples.
print(f'full data after first tokenization:---------------------------------------------------------------' )
for i in tokenized_sentences:
    print(i)

### Adding special tokens:
tokenized_sentences_new = []
max_length = 0
for tokenized_sent in tokenized_sentences:
    tokenized_sentence_new = ['<bos>'] + tokenized_sent + ['<eos>']
    tokenized_sentences_new.append(tokenized_sentence_new)
    max_length = max(max_length, len(tokenized_sentence_new))
print(f'max length : {max_length}')
print(f'full data after adding <bos> & <eos>:---------------------------------------------------------------' )
for i in tokenized_sentences_new:
    print(i)
### Adding special tokens:
tokenized_sentences_new = []
max_length = 0
for tokenized_sent in tokenized_sentences:
    tokenized_sentence_new = ['<bos>'] + tokenized_sent + ['<eos>']
    tokenized_sentences_new.append(tokenized_sentence_new)
    max_length = max(max_length, len(tokenized_sentence_new))
print(f'max length : {max_length}')
print(f'full data after adding <bos> & <eos>:---------------------------------------------------------------' )
for i in tokenized_sentences_new:
    print(i)

### It is observed that all have different lengths and max is 18, so lets do padding
###  to maintain same length for each sentence.
for i in range(len(tokenized_sentences_new)):
    tokenized_sentences_new[i] = tokenized_sentences_new[i] + ['<pad>'] * (max_length - len(tokenized_sentences_new[i]))

print(f'full data after padding :---------------------------------------------------------------' )
for i in tokenized_sentences_new:
    print(i)

### "Vocabulary Building" or "Vocabulary Construction":
from torchtext.vocab import build_vocab_from_iterator
vocab = build_vocab_from_iterator(tokenized_sentences_new, specials=["<unk>"]) 
vocab.set_default_index(vocab["<unk>"]) 

vocab = build_vocab_from_iterator(tokenized_sentences_new, specials=["<pad>", "<bos>", "<eos>", "<unk>"])
# this will give indexs : {'<pad>': 0, '<bos>': 1, '<eos>': 2, '<unk>': 3}
# It is required to provide unique index to each spl token for the model to differentiate each token separately,
# or else it will be problematic when model predicts 0 index, and it is difficult to decide which spl token it is refering to. 
#: It is a common convention to assign the padding token the index 0, so keep <pad> at first,
#: and for rest of the tokens, any number is provided. 

### Indexing
indexed_tokens = []
for tokenized_sent in tokenized_sentences_new:
    indexed_tokens.append([vocab[x] for x in tokenized_sent])
print(f'indexed last sample: {indexed_tokens[5]}')

print(f'full data after padding :---------------------------------------------------------------' )
for i in indexed_tokens:
    print(i)



In [7]:

sentences = [
    "I am Vamshidhar H K, working as a data scientist at Flytxt",
    "I am a native of Andhra pradesh",
    "I am passionate about data analytics in various domains Teleco, banking and health care",
    "I am currnelty focussed on leanring NLP from Coursera",
    "I admire proff. Gilbert strang as he teaches Maths in a most simplest way.",
    "You are awesome!"
]

### Manully processing the data:

In [26]:
### Tokenization:
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")

tokenized_sentences = []
for sent in sentences:
    tokenized_sentences.append(tokenizer(sent)) # tokenizer requires each sample and not the list of samples.
print(f'full data after first tokenization:---------------------------------------------------------------' )
for i in tokenized_sentences:
    print(i)

full data after first tokenization:---------------------------------------------------------------
['i', 'am', 'vamshidhar', 'h', 'k', ',', 'working', 'as', 'a', 'data', 'scientist', 'at', 'flytxt']
['i', 'am', 'a', 'native', 'of', 'andhra', 'pradesh']
['i', 'am', 'passionate', 'about', 'data', 'analytics', 'in', 'various', 'domains', 'teleco', ',', 'banking', 'and', 'health', 'care']
['i', 'am', 'currnelty', 'focussed', 'on', 'leanring', 'nlp', 'from', 'coursera']
['i', 'admire', 'proff', '.', 'gilbert', 'strang', 'as', 'he', 'teaches', 'maths', 'in', 'a', 'most', 'simplest', 'way', '.']
['you', 'are', 'awesome', '!']


In [27]:
### Adding special tokens:
tokenized_sentences_new = []
max_length = 0
for tokenized_sent in tokenized_sentences:
    tokenized_sentence_new = ['<bos>'] + tokenized_sent + ['<eos>']
    tokenized_sentences_new.append(tokenized_sentence_new)
    max_length = max(max_length, len(tokenized_sentence_new))
print(f'max length : {max_length}')
print(f'full data after adding <bos> & <eos>:---------------------------------------------------------------' )
for i in tokenized_sentences_new:
    print(i)

max length : 18
full data after adding <bos> & <eos>:---------------------------------------------------------------
['<bos>', 'i', 'am', 'vamshidhar', 'h', 'k', ',', 'working', 'as', 'a', 'data', 'scientist', 'at', 'flytxt', '<eos>']
['<bos>', 'i', 'am', 'a', 'native', 'of', 'andhra', 'pradesh', '<eos>']
['<bos>', 'i', 'am', 'passionate', 'about', 'data', 'analytics', 'in', 'various', 'domains', 'teleco', ',', 'banking', 'and', 'health', 'care', '<eos>']
['<bos>', 'i', 'am', 'currnelty', 'focussed', 'on', 'leanring', 'nlp', 'from', 'coursera', '<eos>']
['<bos>', 'i', 'admire', 'proff', '.', 'gilbert', 'strang', 'as', 'he', 'teaches', 'maths', 'in', 'a', 'most', 'simplest', 'way', '.', '<eos>']
['<bos>', 'you', 'are', 'awesome', '!', '<eos>']


In [28]:
### It is observed that all have different lengths and max is 18, so lets do padding
###  to maintain same length for each sentence.
for i in range(len(tokenized_sentences_new)):
    tokenized_sentences_new[i] = tokenized_sentences_new[i] + ['<pad>'] * (max_length - len(tokenized_sentences_new[i]))

print(f'full data after padding :---------------------------------------------------------------' )
for i in tokenized_sentences_new:
    print(i)

full data after padding :---------------------------------------------------------------
['<bos>', 'i', 'am', 'vamshidhar', 'h', 'k', ',', 'working', 'as', 'a', 'data', 'scientist', 'at', 'flytxt', '<eos>', '<pad>', '<pad>', '<pad>']
['<bos>', 'i', 'am', 'a', 'native', 'of', 'andhra', 'pradesh', '<eos>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']
['<bos>', 'i', 'am', 'passionate', 'about', 'data', 'analytics', 'in', 'various', 'domains', 'teleco', ',', 'banking', 'and', 'health', 'care', '<eos>', '<pad>']
['<bos>', 'i', 'am', 'currnelty', 'focussed', 'on', 'leanring', 'nlp', 'from', 'coursera', '<eos>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']
['<bos>', 'i', 'admire', 'proff', '.', 'gilbert', 'strang', 'as', 'he', 'teaches', 'maths', 'in', 'a', 'most', 'simplest', 'way', '.', '<eos>']
['<bos>', 'you', 'are', 'awesome', '!', '<eos>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad

In [31]:
### "Vocabulary Building" or "Vocabulary Construction":
from torchtext.vocab import build_vocab_from_iterator
vocab = build_vocab_from_iterator(tokenized_sentences_new, specials=["<unk>"]) 
vocab.set_default_index(vocab["<unk>"]) 

vocab = build_vocab_from_iterator(tokenized_sentences_new, specials=["<pad>", "<bos>", "<eos>", "<unk>"])
# this will give indexs : {'<pad>': 0, '<bos>': 1, '<eos>': 2, '<unk>': 3}
# It is required to provide unique index to each spl token for the model to differentiate each token separately,
# or else it will be problematic when model predicts 0 index, and it is difficult to decide which spl token it is refering to. 
#: It is a common convention to assign the padding token the index 0, so keep <pad> at first,
#: and for rest of the tokens, any number is provided. 

# Assign specific indices if required
"""
vocab.get_stoi()["<pad>"] = 0
vocab.get_stoi()["<bos>"] = 1
vocab.get_stoi()["<eos>"] = 2
vocab.get_stoi()["<unk>"] = 3
"""


### Indexing
indexed_tokens = []
for tokenized_sent in tokenized_sentences_new:
    indexed_tokens.append([vocab[x] for x in tokenized_sent])
print(f'indexed last sample: {indexed_tokens[5]}')

print(f'full data after padding :---------------------------------------------------------------' )
import torch
for i in indexed_tokens:
    print(torch.tensor(i))



indexed last sample: [1, 53, 18, 20, 12, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
full data after padding :---------------------------------------------------------------
tensor([ 1,  4,  5, 49, 30, 33,  7, 52,  9,  6, 10, 44, 19, 26,  2,  0,  0,  0])
tensor([ 1,  4,  5,  6, 37, 39, 17, 42,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0])
tensor([ 1,  4,  5, 41, 13, 10, 15, 11, 50, 25, 48,  7, 21, 16, 32, 22,  2,  0])
tensor([ 1,  4,  5, 24, 27, 40, 34, 38, 28, 23,  2,  0,  0,  0,  0,  0,  0,  0])
tensor([ 1,  4, 14, 43,  8, 29, 46,  9, 31, 47, 35, 11,  6, 36, 45, 51,  8,  2])
tensor([ 1, 53, 18, 20, 12,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])


## Using CustomDataset class and collate function.

In [34]:
# Define a custom data set
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, sentences):
        self.sentences = sentences
        self.tokenizer = tokenizer
        self.vocab = vocab

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        return self.sentences[idx]

# Tokenizer
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")

# Build vocabulary and include special tokens
special_tokens = ["<pad>", "<bos>", "<eos>", "<unk>"]
vocab = build_vocab_from_iterator(map(tokenizer, sentences), specials=special_tokens)

# Set the default index to handle out-of-vocabulary (OOV) tokens
vocab.set_default_index(vocab["<unk>"])

# Create an instance of your custom data set
custom_dataset = CustomDataset(sentences)

print("Custom Dataset Length:", len(custom_dataset))
print("Sample Items:")
for i in range(6):
    sample_item = custom_dataset[i]
    print(f"Item {i + 1}: {sample_item}")

Custom Dataset Length: 6
Sample Items:
Item 1: I am Vamshidhar H K, working as a data scientist at Flytxt
Item 2: I am a native of Andhra pradesh
Item 3: I am passionate about data analytics in various domains Teleco, banking and health care
Item 4: I am currnelty focussed on leanring NLP from Coursera
Item 5: I admire proff. Gilbert strang as he teaches Maths in a most simplest way.
Item 6: You are awesome!


In [38]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    # Pad sequences within the batch to have equal lengths
    tensor_batch=[]
    for sample in batch:
        #basic tokenization
        tokens = tokenizer(sample)
        #special tokenization
        tokens = ['<bos>'] + tokens + ['<eos>']
        # Vocabulary Building
        tensor_batch.append(torch.tensor([vocab[token] for token in tokens]))
         
    # Dynamic Padding Within Batches
    padded_batch = pad_sequence(tensor_batch,batch_first=True)
    return padded_batch

dataloader = DataLoader(custom_dataset, batch_size=2, shuffle=False, collate_fn=collate_fn)

for batch in dataloader:
    print('batch splitter -----------------')
    print(batch)

# Note:
# dynamic padding is preferred,as the batch is padded only to the length of its longest sequence, 
# minimizing the number of padding tokens and making training more efficient.

batch splitter -----------------
tensor([[ 1,  4,  5, 49, 30, 33,  7, 52,  9,  6, 10, 44, 19, 26,  2],
        [ 1,  4,  5,  6, 37, 39, 17, 42,  2,  0,  0,  0,  0,  0,  0]])
batch splitter -----------------
tensor([[ 1,  4,  5, 41, 13, 10, 15, 11, 50, 25, 48,  7, 21, 16, 32, 22,  2],
        [ 1,  4,  5, 24, 27, 40, 34, 38, 28, 23,  2,  0,  0,  0,  0,  0,  0]])
batch splitter -----------------
tensor([[ 1,  4, 14, 43,  8, 29, 46,  9, 31, 47, 35, 11,  6, 36, 45, 51,  8,  2],
        [ 1, 53, 18, 20, 12,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
